/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CoreBtn {
    }
}
declare global {
    interface HTMLCoreBtnElement extends Components.CoreBtn, HTMLStencilElement {
    }
    var HTMLCoreBtnElement: {
        prototype: HTMLCoreBtnElement;
        new (): HTMLCoreBtnElement;
    };
    interface HTMLElementTagNameMap {
        "core-btn": HTMLCoreBtnElement;
    }
}
declare namespace LocalJSX {
    interface CoreBtn {
    }
    interface IntrinsicElements {
        "core-btn": CoreBtn;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "core-btn": LocalJSX.CoreBtn & JSXBase.HTMLAttributes<HTMLCoreBtnElement>;
        }
    }
}
