/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CoreBtn {
        "type": string;
    }
    interface CoreSpinner {
        "color": string;
        "type": string;
    }
}
declare global {
    interface HTMLCoreBtnElement extends Components.CoreBtn, HTMLStencilElement {
    }
    var HTMLCoreBtnElement: {
        prototype: HTMLCoreBtnElement;
        new (): HTMLCoreBtnElement;
    };
    interface HTMLCoreSpinnerElement extends Components.CoreSpinner, HTMLStencilElement {
    }
    var HTMLCoreSpinnerElement: {
        prototype: HTMLCoreSpinnerElement;
        new (): HTMLCoreSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "core-btn": HTMLCoreBtnElement;
        "core-spinner": HTMLCoreSpinnerElement;
    }
}
declare namespace LocalJSX {
    interface CoreBtn {
        "type"?: string;
    }
    interface CoreSpinner {
        "color"?: string;
        "type"?: string;
    }
    interface IntrinsicElements {
        "core-btn": CoreBtn;
        "core-spinner": CoreSpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "core-btn": LocalJSX.CoreBtn & JSXBase.HTMLAttributes<HTMLCoreBtnElement>;
            "core-spinner": LocalJSX.CoreSpinner & JSXBase.HTMLAttributes<HTMLCoreSpinnerElement>;
        }
    }
}
